#!/bin/bash
# Backup all the files in the current directory to a new one

set -u
set -e

#>----------------------------------------------------------
# Return the required value inside config.txt
# Globals:
#   None
# Arguments:
#   $1 - Name of the required value
# Returns:
#   value
#>----------------------------------------------------------
get_data_from_config(){
	local value=$(cat config.txt | grep "^$1" | cut -f 2 -d "=")
	echo $value
}

#>----------------------------------------------------------
# Return the ID of the new backup folder by finding the amount
# of current folders inside the given path
# Globals:
#   None
# Arguments:
#   $1 - Path to folders
# Returns:
#   id
#>----------------------------------------------------------
get_new_backup_id(){
	local id=$(ls -l $1 | grep "^d" | wc -l)
	echo "Backup#$id"
}

echo "Backing up..."

# Create a new backups folder if one doesnt exists at the given path
backups_path=$(get_data_from_config "PATH_TO_BACKUPS")
mkdir -p $backups_path

# Generate a new backup ID
new_backup=$(get_new_backup_id $(get_data_from_config "PATH_TO_BACKUPS"))

# Create a new backup folder inside the backups folder
backup_path="$backups_path/$new_backup"
mkdir -p $backup_path

# Copy all the files inside the current folder into the backups folder
# For every file, inform the user that its been backed up
for file in $(ls *.txt)
do
	cp $file $backup_path
	echo $file "Has been backed up into" $backup_path
done

echo "Done backing up"
