#!/bin/bash
# Backup all the files in the current directory to a new one

set -u
set -e

# Initalize Constants
PATH_TO_CONFIG=$(find $(dirname $0) -name "config.txt")

#>----------------------------------------------------------
# Return the required value inside config.txt
# Globals:
#   None
# Arguments:
#   $1 - Name of the required value
# Returns:
#   value
#>----------------------------------------------------------
get_data_from_config(){
	local value=$(cat < $PATH_TO_CONFIG | grep "^$1" | cut -f 2 -d "=")
	echo $value
}

#>----------------------------------------------------------
# Return the ID of the new backup folder by finding the amount
# of current folders inside the given path
# Globals:
#   None
# Arguments:
#   $1 - Path to folders
# Returns:
#   id
#>----------------------------------------------------------
get_new_backup_id(){
	local id=$(ls -l $1 | grep "^d" | wc -l)
	echo "Backup#$id"
}


# Create a new backups folder if one doesnt exists at the given path
backups_path=$(get_data_from_config "PATH_TO_BACKUPS")
mkdir -p $backups_path

# Generate a new backup ID
new_backup_name=$(get_new_backup_id $(get_data_from_config "PATH_TO_BACKUPS"))

# Create a new backup folder inside the backups folder
backup_path="$backups_path/$new_backup_name"
mkdir -p $backup_path

# Copy all the files inside the current folder into the backups folder
# Inform the user of the location of the backup
cp -rn $(ls) $backup_path
echo "Files have been backed up into" $backup_path
